apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: test1
  name: kube-pod-not-ready
  namespace: monitor
spec:
  groups:
  - name: test-pods-alerts
    rules:
    - alert: KubernetesPodNotHealthy
      expr: sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"}) > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod {{ $labels.pod }} not healthy"
        description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is not in Running state."

    - alert: KubernetesPodCrashLooping
      expr: increase(kube_pod_container_status_restarts_total[5m]) > 2
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod {{ $labels.pod }} crash looping"
        description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} restarted multiple times."

