# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: backend-log-persistance
# spec:
#   storageClassName: nfs-client
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 100Mi